LMMProject/LMMProject/Controllers/ADMINController.cs
using LMMProject.Data;
using LMMProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LMMProject.Controllers
{
    public class ADMINController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IHttpContextAccessor _Accessor;
        public ADMINController(AppDbContext context, IHttpContextAccessor accessor)
        {
            _context = context;
            _Accessor = accessor;
        }
        public IActionResult Dashboard()
        {
            return View();
        }

        public IActionResult Infor()
        {
            string userName=_Accessor.HttpContext.Session.GetString("Username");
            var Account = _context.Account.Include(p => p.Role).FirstOrDefault(pro => pro.UserName.Equals(userName));
            return View(Account);
        }
        [HttpPost]
        public async Task<IActionResult> Infor(Account account)
        {
            var accountChange = new Account();
            accountChange = _context.Account.Include(p => p.Role).FirstOrDefault(pro => pro.UserName.Equals(account.UserName));
            accountChange.UserName=account.UserName;
            accountChange.Fullname=account.Fullname;
            accountChange.Address=account.Address;
            accountChange.Phone=account.Phone;
            accountChange.Gender=account.Gender;
            accountChange.Birthday=account.Birthday;
           _context.Account.Update(accountChange);
           _context.SaveChanges();
            TempData["Error"] = "Change information successful !";
            return RedirectToAction("Infor");
        }

        public IActionResult ListOfCurriculum()
        {
            var listCurriculum = _context.Curriculum.Include(p => p.Decision).ToList();
            return View(listCurriculum);
        }
        public IActionResult ListOfCombo()
        {
            var listCombo = _context.Combo.Include(a => a.Curriculum).ToList();
            return View(listCombo);
        }
        public IActionResult ComboSubject()
        {
            var ComboSubject = _context.Combo_Subject.Include(a => a.Subject).Include(p=> p.Combo).ToList();
            return View(ComboSubject); 
        }

    }
}

LMMProject/LMMProject/Controllers/ADMINCurriculaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMMProject.Data;
using LMMProject.Models;

namespace LMMProject.Controllers
{
    public class ADMINCurriculaController : Controller
    {
        private readonly AppDbContext _context;

        public ADMINCurriculaController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Curricula
        public async Task<IActionResult> Index()
        {
            IEnumerable<Curriculum> appDbContext = _context.Curriculum.Include(c => c.Decision).ToList();
            return View(appDbContext);
        }

        // GET: Curricula/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Curriculum == null)
            {
                return NotFound();
            }

            var curriculum = await _context.Curriculum
                .Include(c => c.Decision)
                .FirstOrDefaultAsync(m => m.CurriculumId == id);
            var curri_sub= _context.Curriculum_Subject.Include(p => p.Subject).Where(pro => pro.CurriculumId==id).OrderBy(p=>p.Semester).ToList();
            ViewBag.Curri_sub=curri_sub;
            if (curriculum == null)
            {
                return NotFound();
            }

            return View(curriculum);
        }

        // GET: Curricula/Create
        public IActionResult Create()
        {
            ViewData["DecisionNo"] = new SelectList(_context.Decision, "DecisionNo", "DecisionNo");
            return View();
        }

         // POST: Curricula/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CurriculumId,CurriculumCode,NameVn,NameEn,Decription,DecisionNo,TotalCredit,IsActive")] Curriculum curriculum)
        {
            
            if (ModelState.IsValid)
            {
                Curriculum checkCode= await _context.Curriculum.Include(p => p.Decision).FirstOrDefaultAsync(pro => pro.CurriculumCode.Equals(curriculum.CurriculumCode));
                if (checkCode == null)
                {
                    _context.Add(curriculum);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["Error"] = "Wrong: Curriculum is already exist !";
                }
            }
            ViewData["DecisionNo"] = new SelectList(_context.Decision, "DecisionNo", "DecisionNo", curriculum.DecisionNo);
            return View(curriculum);
        }

        // GET: Curricula/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Curriculum == null)
            {
                return NotFound();
            }

            var curriculum = await _context.Curriculum.FindAsync(id);
            if (curriculum == null)
            {
                return NotFound();
            }
            ViewData["DecisionNo"] = new SelectList(_context.Decision, "DecisionNo", "DecisionNo", curriculum.DecisionNo);
            return View(curriculum);
        }

        // POST: Curricula/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CurriculumId,CurriculumCode,NameVn,NameEn,Decription,DecisionNo,TotalCredit,IsActive")] Curriculum curriculum)
        {
            if (id != curriculum.CurriculumId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(curriculum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CurriculumExists(curriculum.CurriculumId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DecisionNo"] = new SelectList(_context.Decision, "DecisionNo", "DecisionNo", curriculum.DecisionNo);
            return View(curriculum);
        }

        // GET: Curricula/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Curriculum == null)
            {
                return NotFound();
            }

            var curriculum = await _context.Curriculum
                .Include(c => c.Decision)
                .FirstOrDefaultAsync(m => m.CurriculumId == id);
            if (curriculum == null)
            {
                return NotFound();
            }
            return View(curriculum);
        }

        // POST: Curricula/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Curriculum == null)
            {
                return Problem("Entity set 'AppDbContext.Curriculum'  is null.");
            }
            //DA SUA THEM DELETE 
            var curriculum = await _context.Curriculum.FindAsync(id);
            var check = _context.Curriculum_Subject.Where(p => p.CurriculumId == id).ToList();
            var combo = _context.Combo.Where(p => p.CurriculumId == id).ToList();
            foreach (var item in combo)
            {
                var com_sub = _context.Combo_Subject.Where(p => p.ComboId == item.ComboId).ToList();
                _context.Combo_Subject.RemoveRange(com_sub);
            }
            _context.Combo.RemoveRange(combo);
            _context.Curriculum_Subject.RemoveRange(check);
            _context.Curriculum.Remove(curriculum);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// PHAN THEM
        public async Task<IActionResult> AddSubject(string semester)
        {
            string add = Request.Form["add"];
            int curriId = Convert.ToInt32(Request.Form["curriId"]);
            
            if (add != null && !add.Trim().Equals(""))
            {
                Subject sj = _context.Subject.Include(p => p.Status).FirstOrDefault(pro => pro.SubjectCode.Equals(add.Trim()));
                if (sj != null)
                {

                    var check = _context.Curriculum_Subject.Where(p => p.CurriculumId == curriId).ToList();
                    CurriculumSubject check_element = (from element in check
                                        where element.SubjectCode.Trim().Equals(sj.SubjectCode.Trim())
                                        select element).FirstOrDefault();
                    if (check_element==null)
                    {
                        
                        CurriculumSubject cu_sub = new CurriculumSubject();
                        cu_sub.SubjectCode = sj.SubjectCode;
                        cu_sub.CurriculumId = curriId;
                        if (semester != null)
                        {
                            int semester_int = Convert.ToInt32(semester);
                            cu_sub.Semester = semester_int;
                        }
                        _context.Curriculum_Subject.Add(cu_sub);
                        _context.SaveChanges();
                        return new RedirectResult(url: "/ADMINCurricula/Details/" + curriId, permanent: true, preserveMethod: true);
                    }
                    else
                    {
                        TempData["error"] = "Sorry: This subject already exists, please add another subject !";
                        return new RedirectResult(url: "/ADMINCurricula/Details/" + curriId, permanent: true, preserveMethod: true);
                    }
                }
                else
                {
                    TempData["error"] = "Sorry: Subject not found, please enter valid subject code !";
                    return new RedirectResult(url: "/ADMINCurricula/Details/" + curriId, permanent: true, preserveMethod: true);
                }
            }
            TempData["error"] = "Sorry: Subject not found, please enter valid subject code !";
            return new RedirectResult(url: "/ADMINCurricula/Details/" + curriId, permanent: true, preserveMethod: true);
        }

        /// PHAN THEM
        public async Task<IActionResult> DeleteSubject(int id, int cu_sub_ID)
        {
            //CurriculumSubject cu_sub = new CurriculumSubject();
            //cu_sub.SubjectCode = subCode;
            //cu_sub.CurriculumId = id;
            CurriculumSubject cu_sub= _context.Curriculum_Subject.Find(cu_sub_ID);
            var combo = _context.Combo.Where(p => p.CurriculumId==id).ToList();
            foreach(var item in combo)
            {
                var com_sub = _context.Combo_Subject.Where(p => p.ComboId==item.ComboId).ToList();
               foreach(var  com in com_sub)
                {
                   if(com.SubjectCode.Equals(cu_sub.SubjectCode))
                    {
                        _context.Combo_Subject.Remove(com);
                        _context.SaveChanges();
                    }
                }
            }
            _context.Curriculum_Subject.Remove(cu_sub);
            _context.SaveChanges();

LMMProject/LMMProject/Views/ADMINCurricula/Create.cshtml
@model LMMProject.Models.Curriculum

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/delete.css">
</head>
<body>
    <div class="color">
        <h1> Create Curriculum</h1>
    </div>
    <div class="container-center">
        @if (TempData["Error"] != null)
        {
            <div class="col-md-12 alert alert-danger">
                <span style="color:red"><b>Sorry!</b> - @TempData["Error"]</span>
            </div>
        }
        <div class="col-md-4">
            <div class="square-container">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group mb-3">
                        <label asp-for="CurriculumCode" class="control-label"></label>
                        <input asp-for="CurriculumCode" class="form-control" />
                        <span asp-validation-for="CurriculumCode" class="text-danger" style="color:red"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="NameVn" class="control-label"></label>
                        <input asp-for="NameVn" class="form-control" />
                        <span asp-validation-for="NameVn" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="NameEn" class="control-label"></label>
                        <input asp-for="NameEn" class="form-control" />
                        <span asp-validation-for="NameEn" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Decription" class="control-label"></label>
                        <input asp-for="Decription" class="form-control" />
                        <span asp-validation-for="Decription" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="DecisionNo" class="control-label"></label>
                        <select asp-for="DecisionNo" class="form-control" asp-items="ViewBag.DecisionNo"></select>
                    </div>
                    <div class="form-group mb-3">
                        <input type="submit" value="Create" class="btn btn-success btn btn-primary" /> |
                        <a asp-action="Index" class="btn btn-primary">Back to List</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
</body>
</html>

LMMProject/LMMProject/Views/ADMINCurricula/Delete.cshtml
@model LMMProject.Models.Curriculum

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/delete-detail.css">
    <title>Delete</title>
</head>
<body>
    <div class="color">
        <h1> Delete Curriculum</h1>
    </div>
    <div>
        <div class="container-center">
            <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CurriculumCode)
                </th>
                <td>
                    @Html.DisplayFor(model => model.CurriculumCode)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NameVn)
                </th>
                <td>
                    @Html.DisplayFor(model => model.NameVn)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NameEn)
                </th>
                <td>
                    @Html.DisplayFor(model => model.NameEn)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Decription)
                </th>
                <td>
                    @Html.DisplayFor(model => model.Decription)
                </td>
            </tr>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Decision)
                </th>
                <td>
                    @Html.DisplayFor(model => model.Decision.DecisionNo)
                </td>
            </tr>
        </table>
            <div class="delete-section">
                <h4>Are you sure you want to delete?</h4>
                <form asp-action="Delete">
                    <input type="hidden" asp-for="CurriculumId" />
                    <input type="submit" value="Delete" class="btn btn-danger" class="btn btn-primary" /> |
                    <a asp-action="Index" class="btn btn-primary">Back to List</a>
                </form>
            </div>
        </div>       
    </div>
</body>
</html>

LMMProject/LMMProject/Views/ADMINCurricula/Details.cshtml
@model LMMProject.Models.Curriculum

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/curri-details.css">
    <title >Details</title>
</head>
<body>

    <div class="curri-details">
        <div class="navbar">
            <img src="~/image/istockphoto-1138089745-170667a.jpg" class="logo">
            <ul>
                <li><a asp-controller="ADMIN" asp-action="Dashboard">Home</a></li>
                <li><a asp-action="Index">Back to List</a></li>
            </ul>
        </div>
        <div class="content">
            <b>
                <h1>Learning Materials Management</h1>
                <p>Curriculum Details</p>
            </b>
        </div>
        <table class="table">
            <tr>
                <th>Curriculum Code:</th>
                <td>@Model.CurriculumCode</td>
            </tr>
            <tr>
                <th>Name:</th>
                <td>
                    @Model.NameVn
                </td>
            </tr>
            <tr>
                <th>English Name:</th>
                <td>@Model.NameEn</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>
                    @Model.Decription
                </td>
            </tr>
            <tr>
                <th>DecisionNo MM/dd/yyyy:</th>
                <td>@Model.DecisionNo</td>
            </tr>

            <tr>
                <th></th>
                <td>
                    <div>
                        <a asp-action="Edit" asp-route-id="@Model?.CurriculumId" class="btn btn-primary">Edit</a> |
                        <a asp-controller="ADMINCombo" asp-action="Index" asp-route-id="@Model?.CurriculumId" class="btn btn-primary"> View Combo</a>                        
                    </div>
                </td>
            </tr>
        </table>
        <div class="table-container">
            @if (TempData["error"] != null)
            {              
                    <p><b>@TempData["error"]</b></p>               
            }
                       
            <table class="table-2">   
                
                <thead>
                    <tr>
                        <td colspan="6">
                            <div class="form-container">
                                <form asp-controller="ADMINCurricula" asp-action="AddSubject">
                                    <div class="form-group mb-3">
                                        <label for="subject-code">Enter Subject code:</label>
                                        <input type="hidden" name="curriId" value="@Model?.CurriculumId" />
                                        <input type="text" id="subject-code" name="add" />
                                    </div>
                                    <div class="form-group mb-3">
                                        <label for="semester">Enter semester:</label>
                                        <input type="number" id="semester" name="semester" />
                                    </div>                                  
                                        <button type="submit" class="btn btn-primary">ADD SUBJECT</button>                             
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <th>Subject Code</th>
                        <th>Subject Name</th>
                        <th>Semester</th>
                        <th>Status</th>
                        <th>PreRequisite </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.Curri_sub)
                    {
                <tr>
                            <td>@item.SubjectCode</td>
                            <td>@item.Subject.SubjectNameEn</td>
                            <td>@item.Semester</td>
                            <td>@item.Subject.StatusId</td>
                            <td>@item.Subject.PreRequisite </td>
                            <td><a asp-controller="ADMINCurricula" asp-action="DeleteSubject" asp-route-id="@Model?.CurriculumId" asp-route-cu_sub_ID="@item.id"><button type="button" class="btn btn-primary"><span></span> DELETE</button></a></td>
                </tr>
                    }
                </tbody>
            </table>
        </div>
        
    </div>


</body>
</html>

LMMProject/LMMProject/Views/ADMINCurricula/Edit.cshtml
@model LMMProject.Models.Curriculum

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/delete.css">
</head>
<body>
    <div class="color">
        <h1> Edit Curriculum</h1>
    </div>

    <div class="container-center">
        <div class="col-md-4">
            <div class="square-container">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="CurriculumId" />
                    <div class="form-group mb-3">
                        <label asp-for="CurriculumCode" class="control-label"></label>
                        <input asp-for="CurriculumCode" class="form-control" readonly />
                        <span asp-validation-for="CurriculumCode" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="NameVn" class="control-label"></label>
                        <input asp-for="NameVn" class="form-control" />
                        <span asp-validation-for="NameVn" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="NameEn" class="control-label"></label>
                        <input asp-for="NameEn" class="form-control" />
                        <span asp-validation-for="NameEn" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Decription" class="control-label"></label>
                        <input asp-for="Decription" class="form-control" />
                        <span asp-validation-for="Decription" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="DecisionNo" class="control-label"></label>
                        <select asp-for="DecisionNo" class="form-control" asp-items="ViewBag.DecisionNo"></select>
                        <span asp-validation-for="DecisionNo" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <input type="submit" value="Save" class="btn btn-success btn btn-primary" /> |
                        <a asp-action="Index" class="btn btn-primary">Back to List</a>
                    </div>
                </form>
            </div>
        </div>

    </div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

</body>
</html>

LMMProject/LMMProject/Views/ADMINCurricula/Index.cshtml
@model IEnumerable<LMMProject.Models.Curriculum>
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/curri-index.css">
</head>
<body>
    <div class="curri-details">
        <div class="navbar">
            <img src="~/image/istockphoto-1138089745-170667a.jpg" class="logo">
            <ul>
                <li><a asp-controller="ADMIN" asp-action="Dashboard">Home</a></li>
                <li><a asp-action="Create">Create New</a></li>
            </ul>
        </div>
        <div class="content">
            <b>
                <h1>Learning Materials Management</h1>
                <p>Curriculum Listing</p>
            </b>
        </div>
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CurriculumCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NameVn)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NameEn)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Decision)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CurriculumCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NameVn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NameEn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Decision.DecisionNo)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.CurriculumId" class="btn btn-primary">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.CurriculumId" class="btn btn-primary">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.CurriculumId" class="btn btn-primary">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</body>
</html>